### ISSUE TITLE
Translate and Compress Properties in RESOURCES are not pulled/pushed correctly

### ISSUE THREAD

**Issue by horvathkevin** [atSCM/atscm#134]
*Translate and Compress Properties in RESOURCES are not pulled/pushed correctly*

**Steps to reproduce error**

 - Add Translate/Compress property to SYSTEM.LIBARY.ATVISE.RESOURCES/index.htm
 - Perform atscm pull
 - Translate property is not mapped as child node

*Screenshot*
![image](https://user-images.githubusercontent.com/30588277/36299433-302401ec-12fd-11e8-8736-517a07572337.png)

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | *Windows* |
| atscm         |         0.7.0 beta.1 | 
| atscm-cli     |     0.4.0 | 
| atvise server | 3.2.0 |
| node          |          8.9.4 | 
| npm           |           5.5.1 | 
 
</details>

<details><summary><strong>Project configuration</strong></summary>

```javascript
// Atviseproject.babel.js

// Insert contents of Atviseproject here
```

</details>

**Comment by LukasHechenberger** [comment]
Closing in favor of #170
