### ISSUE TITLE
Push task freeze when referenced object types are pushed 

### ISSUE THREAD

**Issue by horvathkevin** [atSCM/atscm#135]
*Happens in customer specific project. 
 When ObjectTypes are pushed, the push tasks freezes and stops pushing files*

**Steps to reproduce error**

 - *Initialize new atscm project*
 - *Start referred nodes.db*
 - *Perform atscm pull*
 - *Perform atscm push --> push tasks freezes*

Customers project database is available on request.

**Original error message**
No error message is shown

*Insert error message (or screenshot) here*
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | *Windows 10 64 Bit* |
| atscm         |         0.7.0 beta.1 | 
| atscm-cli     |     0.4.0 | 
| atvise server | 3.2.0 |
| node          | 8.9.4 | 
| npm           | 5.5.2 | 
 
</details>

<details><summary><strong>Project configuration</strong></summary>

```javascript
// Atviseproject.babel.js

// Insert contents of Atviseproject here
 /**
   * The atvise-server nodes that atvise-scm should sync. Defaults to
   * `['ns=1;s=AGENT', 'ns=1;s=SYSTEM', 'ns=1;s=ObjectTypes.PROJECT']`
   * @type {String[]|NodeId[]}
   */
  static get nodes() {
    return [
      new NodeId('ObjectTypes.PROJECT.UTILITIES.CMS_TYPES.CMS'),
    ];
  }

</details>

**Comment by LukasHechenberger** [comment]
Assuming this is fixed in the current release - Feel free to reopen this issue otherwise.
