### ISSUE TITLE
Unable to map <...>.SortOrder: Cannot read property trim of null

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#155]
When doing atscm pull I get these messages.

**Unable to map <...>.SortOrder: Cannot read property trim of null**

Pull continues, but is complaining about it every time. Is this important? Does it mean we have a broken nodes.db?

**Steps to reproduce error**

 - atscm pull

**Original error message**

![image](https://user-images.githubusercontent.com/34569639/37451052-94ae5b56-2830-11e8-9773-60a39f1c9dbe.png)
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 x64 |
| atscm         |         0.6.0-beta12 |
| atscm-cli     |     0.4.0 |
| atvise server | v3.2.0 |
| node          |          v9.3.0 | 
| npm           |           5.6.0 |
 
</details>

**Comment by LukasHechenberger** [comment]
This basically means that the display sort order node references nodes (=displays) that don't exist. Correct the sort order in atvise builder or ignore it, it doesn't make any difference to atSCM, as pulled node-files don't have an explicit order.
