### ISSUE TITLE
Watch task does not recognize removal of nodes/objects

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#156]
The watch task does not recognize when i delete 
- QuickDynamics
- Serverscripts
- ObjectDisplays
- Displays 

outside of Atvise Builder

**Steps to reproduce error**

 - atscm pull
 - atscm watch
 - delete one of these

**Original error message**

No Error message
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 x64 |
| atscm         |         0.6.0-beta12 |
| atscm-cli     |     0.4.0 |
| atvise server | v3.2.0 |
| node          |          v9.3.0 | 
| npm           |           5.6.0 |
 
</details>

**Comment by LukasHechenberger** [comment]
Closing in favour of #167
