### ISSUE TITLE
watch task does not recognize newly created display in atvise builder

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#158]
watch task does not recognize newly created display in atvise builder

**Steps to reproduce error**
 - atscm pull
 - atscm watch 
 - create display in atvise builder

**Original error message**

Nothing happens
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 x64 |
| atscm         |         0.6.0-beta12 |
| atscm-cli     |     0.4.0 |
| atvise server | v3.2.0 |
| node          |          v9.3.0 | 
| npm           |           5.6.0 |
 
</details>

**Comment by IngMichaelMayr** [comment]
This also includes the following node types: Serverscript, Object Displays, QuickDynamics, Global Parameters

**Comment by IngMichaelMayr** [comment]
when setting nodesToWatch it seems to work

**Comment by LukasHechenberger** [comment]
This will be *very hard to implement*. This should not have any priority for now.

Closing in favour of #167
