### ISSUE TITLE
watch crashes when creating global font node

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#199]
When creating a new Global Font node with a 
- *<node>.var.string.json
- *<node>.var.string
and changing one of the files. Atscm crashes with the following message:

**Original error message**

![atscmcreateglobalscrash](https://user-images.githubusercontent.com/34569639/40981080-60ee3d32-68da-11e8-9487-149387d6a11d.PNG)
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 x64 |
| atscm         |         v0.6.0-beta34 |
| atscm-cli     |     v0.4.0 |
| atvise server | 3.2.0 |
| node          |          v5.6.0 |
| npm           |           v9.3.0 |
 
</details>

**Comment by LukasHechenberger** [comment]
Closing in favour of #167
