### ISSUE TITLE
Starting watch task does not work sometimes --> freezes

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#202]
Since V0.6.0 it happens nearly every second time I call atscm watch, that the watch task get's stuck at:
stating 'watch'...

**FYI:** In the screenshot I didn't want to wait. But some tries before I waited for 10 minutes and nothing happened!

**Steps to reproduce error**
* atscm watch

**Original error message**

![atscm watch task freeze](https://user-images.githubusercontent.com/34569639/41580750-3eb59194-739c-11e8-9214-3aad8503af45.png)
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 x64 |
| atscm         |         v0.6.0 |
| atscm-cli     |     v0.5.0 |
| atvise server | 3.2.0 |
| node          |          v9.3.0 |
| npm           |           v6.1.0 |
</details>

**Comment by forthnight** [comment]
I have the same problem.  
However, my first line is an error or fallback message from babel.

(This is my first attempt at running this program, so there might be some user errors I am unaware of)


![image](https://user-images.githubusercontent.com/27929979/46458260-78883300-c7b5-11e8-9c9d-387015a61e8a.png)

**Comment by breussm** [comment]
@forthnight 
Is your problem solved in current version?

**Comment by LukasHechenberger** [comment]
Fixed in #369 - run `atscm update` to install atscm v1!
