### ISSUE TITLE
When using atscm with SVN every file is recognized as changed

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#238]
When using atscm with SVN and doing several pulls, every file is recognized as changed by SVN.
I think it is related to the change detection algoythm of SVN.
As far as I could find out, SVN tracks file changes by filetime and date, and content only on diff of the specific file direct.

Therefor all files of atscm file structure will be marked as changed. Although there was no change.
A suggested solution would be to teach atscm to update only files that have been changed on the nodes.db. Maybe with a md5 checksum over the file content.

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 |
| atscm         |         >=1.0.0-beta.13 | 
| atscm-cli     |     0.7.0 | 
| atvise server | 2.5.9 & 3.2.0 |
| node          |          9.3.0 | 
| npm           |           5.6.0 | 
 
</details>

**Comment by LukasHechenberger** [comment]
@IngMichaelMayr could you check out *v1.0.0-beta.16*? It uses checksum comparison to decide if writes are needed when running `atscm pull`.

Migrating: 
- `npm i --save-dev atscm@beta` (or `atscm update --beta`)
- Edit *Atviseproject* to optimise for subversion:
   ```diff
   diff --git a/Atviseproject.js b/Atviseproject.js
   index 7e9c26fd..f1364b80 100755
   --- a/Atviseproject.js
   +++ b/Atviseproject.js
   @@ -55,6 +55,8 @@ class Argonics extends Atviseproject {
        ])
      }
    
   +  static get vcs() { return 'svn'; }
   +
    }
    
    module.exports = { default: Argonics };
   ```
- Run `atscm pull` and compare results

**Comment by IngMichaelMayr** [comment]
Okay, I will have a try on this and report as soon as possible.

**Comment by IngMichaelMayr** [comment]
Check it with beta 18 and 22.
At 18 I saw less files than the in the other versions before. But still a big list of changed files.
With 22 it now seems to work and showing only changed files. I will try it out with this and future versions of atscm in detail tests. Closing this issue for now, though it seems to be solved.
