### ISSUE TITLE
Executing atscm pull several times will add emtpy lines every time to svg file

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#239]
Executing atscm pull several times will add emtpy lines every time to svg file

**Steps to reproduce error**

 - atscm pull
 - check svg file
 - atscm pull
 - check svg file

**Screenshot**

![image](https://user-images.githubusercontent.com/34569639/50144011-5ed39380-02ae-11e9-87ae-5aa75ef423c9.png)

 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 |
| atscm         |         >=1.0.0-beta.13 | 
| atscm-cli     |     0.7.0 | 
| atvise server | 2.5.9 & 3.2.0 |
| node          |          9.3.0 | 
| npm           |           5.6.0 | 
 
</details>

**Comment by LukasHechenberger** [comment]
Did you come across this behaviour in other cases as well? Because the SVG in your screenshot is no valid XML. If you remove the invalid code (line 15 - 20) everything works fine.

**Comment by IngMichaelMayr** [comment]
Yes, I experienced this issue on every svg file in the project tree.

The SVG File has been created by atscm by the first pull. I did not make any changes on it afterwards. If this is true, it would mean that atscm itself creates invalid svg files, as far as I understand.

**Comment by IngMichaelMayr** [comment]
We checked the svg files concerned. And we will adapt them to the tinysvg corresponding format.
Will test it with the new beta version and report back.

**Comment by IngMichaelMayr** [comment]
Checking version beta.22 I recognized, that this svg files no longer appear in the svn commit list. Maybe this is related to solving issue #251 (multiple inline scripts)

**Comment by LukasHechenberger** [comment]
Starting with *1.0.0-beta.23* this should be fixed. In addition a warning is logged when pulling/pushing XML files with text alongside tags.

**Comment by breussm** [comment]
@IngMichaelMayr please check the new version

**Comment by breussm** [comment]
@IngMichaelMayr 
Reminder

**Comment by michaelgrafl** [comment]
This happens to me in version 1.0.0-beta.25 when using span-tags inside of p-tags inside of a foreignObject using the xhtml extension/namespace.

I understand that it's not recommended to mix text nodes and tags in XML documents for semantic reasons, but I think mixing span tags with text nodes is quite common, so it'd be great if this wouldn't pose a problem.

I can easily work around this by wrapping classless span tags around the text nodes, so this isn't a pressing issue. But it'd be nice if I didn't have to do that.
