### ISSUE TITLE
Better error message information

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#250]
When performing an atscm push i got the following error message.

![image](https://user-images.githubusercontent.com/34569639/52276427-76480800-2952-11e9-8e9c-0e29e780708d.png)

Here it would be good to have the full file path to the JSON File creating this error.

**Steps to reproduce error**

 - Happened after SVN Merge --> Some Files were corrupt.

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 |
| atscm         |         >=1.0.0-beta.18 | 
| atscm-cli     |     0.7.0 | 
| atvise server | 2.5.9 & 3.2.0 |
| node          |          9.3.0 |
| npm           |           5.6.0 |
 
</details>

**Comment by LukasHechenberger** [comment]
Starting with *1.0.0-beta.23* node ids are printed alongside errors that occur during transformation.

**Comment by breussm** [comment]
@IngMichaelMayr 
which version you use? in version 1.0.0.39 we implement better errormessages

**Comment by LukasHechenberger** [comment]
Assuming this is fixed in the current release - Feel free to reopen this issue otherwise.
