### ISSUE TITLE
Warning - contains multiple inline scripts

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#251]
When creating a new nodes.db (V3.2.0) and using the code from a ported nodes.db, new nodes will be synced to the atscm file structure.

When this happens I get the following warnings:
![image](https://user-images.githubusercontent.com/34569639/52277970-36831f80-2956-11e9-9f28-cf9ea723dfac.png)

I don't know if its an atscm issue or an atvise issue, but I found it confusing the first time I saw it.

**Steps to reproduce error**

 - push ported atvise code to newly created nodes.db (empty)
 - pull code afterwards

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 |
| atscm         |         >=1.0.0-beta.18 | 
| atscm-cli     |     0.7.0 | 
| atvise server | 2.5.9 & 3.2.0 |
| node          |          9.3.0 | 
| npm           |           5.6.0 | 
 
</details>

**Comment by LukasHechenberger** [comment]
Starting with *v1.0.0-beta.21* atscm reports multiple script tags in your own displays only
