### ISSUE TITLE
pull task doesn't create ./atscm/rename.json file

### ISSUE THREAD

**Issue by michaelgrafl** [atSCM/atscm#259]
If doing a pull results in ID conflicts the console log indicates that a file named *./atscm/rename.json* has been created, which in version 1.0.0-beta.19 doesn't work. (It did work before)

Manually creating the file and mapping the nodes solves the conflicts, but I wouldn't have been able to do this if I hadn't had older rename.js files floating around on my filesystem.

**Steps to reproduce error**

 - Create an atvise project with ambiguous node IDs (e.g. AGENT.OBJECTS.path vs. AGENT.OBJECTS.Path)
 - Initialize a new atscm project
 - Pull
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10.0.17763 |
| atscm         |         1.0.0-beta.19 | 
| atscm-cli     |      0.7.0 | 0.7.0
| atvise server | 3.2.1 |
| node          |          10.13.0 | 
| npm           |           6.8.0 | 
 
</details>

**Comment by LukasHechenberger** [comment]
Thanks for reporting, this issue is fixed in beta 20. Running `npm i --save-dev atscm@beta` will fix it.

**Comment by michaelgrafl** [comment]
Thanks for fixing this issue, but it seems to me that there has been a regression in 1.0.0-beta.41 (or earlier). After pulling a project with conflicts the message to edit ./atscm/rename.json appears, but neither file nor folder seem to have been created.
