### ISSUE TITLE
atscm push task throws timeout error prematurely

### ISSUE THREAD

**Issue by michaelgrafl** [atSCM/atscm#277]
The atscm push task tends to throw and exit with a timeout error at seemingly arbitrary nodes (but at roughly similar time frames).

Increasing the setTimout parameter in .\src\lib\server\Client.js from 5 seconds to 50 seconds solves the issue in this particular case. A smaller increase may have worked as well, but I didn't take the time to try a lower value.

Anyway, it might be prudent to let the user change this value to his needs in the configuration.

**Steps to reproduce error**

 - Not sure how to reproduce this except for decreasing the aforementioned timeout parameter till it breaks.

**Original error message**
```
Michael Grafl@EI-WRK-L-306 c:\r\dorstRepo2
# atscm push
[11:04:05] Using gulpfile c:\r\dorstRepo2\node_modules\atscm\out\Gulpfile.js
[11:04:05] Starting 'push'...
[11:04:14] 'push' errored after 9.01 s
[11:04:14] Error: Unable to connect to opc.tcp://localhost:4841: Connection timed out
    at Timeout.setTimeout (c:\r\dorstRepo2\node_modules\atscm\src\lib\server\Client.js:27:9)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
 - Node: AGENT.DISPLAYS.MAIN.Scrollable_Table.Historylist
 ```
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10.0.17763 |
| atscm         |         1.0.0-beta.24 | 
| atscm-cli     |      0.7.0 | 
| atvise server | 3.2.1 |
| node          |          10.13.0 | 
| npm           |           6.8.0 | 
 
</details>

<details><summary><strong>Project configuration</strong></summary>

```javascript
import { Atviseproject, NodeId } from "atscm";
import { ports } from "./atscm-ports.js";

/**
 * atvise-scm configuration of dorst_ultra.
 */
export default class DorstUltra extends Atviseproject {
  /**
   * The atvise-server's host
   * @type {String}
   */
  static get host() {
    return "localhost";
  }

  /**
   * The atvise-server ports to use.
   * @type {Object}
   * @property {Number} opc The OPC-UA port the atvise-server runs on.
   * @property {Number} http The HTTP port the atvise-server can be reached at.
   */
  static get port() {
    // Please set your local ports in ./atscm-ports.js
    // and do *not* check them in.
    return {
      opc: ports.opc,
      http: ports.http
    };
  }

  static get nodes() {
    return [
      new NodeId("AGENT.DISPLAYS.MAIN"),
      new NodeId("AGENT.DISPLAYS.Default"),
      new NodeId("SYSTEM.LIBRARY.PROJECT.MENUSCRIPTS"),
      new NodeId("SYSTEM.LIBRARY.PROJECT.OBJECTDISPLAYS"),
      new NodeId("SYSTEM.LIBRARY.PROJECT.QUICKDYNAMICS"),
      new NodeId("SYSTEM.LIBRARY.PROJECT.RESOURCES"),
      new NodeId("SYSTEM.LIBRARY.PROJECT.SERVERSCRIPTS"),
      new NodeId("SYSTEM.LIBRARY.PROJECT.WEBMIMETHODS")
    ];
  }
}
```

</details>

**Comment by breussm** [comment]
@michaelgrafl please try new version

**Comment by breussm** [comment]
@michaelgrafl 
Reminder!!!!

**Comment by michaelgrafl** [comment]
This problem doesn't occur in version 1.0.0-beta.41.

**Comment by LukasHechenberger** [comment]
Nice! Thanks for checking
