### ISSUE TITLE
Push to blank nodes.db ends in error

### ISSUE THREAD

**Issue by Grwmagad** [atSCM/atscm#296]
** Error description **
Hey, I am having problems pushing my src files into a blank nodes.db.
The idea is that a colleague can, without copying the nodes.db, create a new nodes.db and push the src into the blank nodes.db. The script crashes with an error.
I tried to delete the src file which causes the crash but the next file causes the next error.
Is that even supported? I always get the error you see below.

**Steps to reproduce error**

- Create a new blank nodes.db and push your old atscm project.

**Original error message**

> Error: Error creating node SYSTEM.LIBRARY.ATVISE.RESOURCES/polyfill.min.js: Script error in 'SYSTEM.LIBRARY.ATVISE.SERVERSCRIPTS.atscm.CreateNode' @ln17,21: TypeError: Cannot call method 'reduce' of undefined

 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | *Windows/MacOS* |
| atscm         |        0.6.0 | 
| atscm-cli     |     0.7.1 | 
| atvise server | atvise server version |
| node          |          11.13.0 | 
| npm           |           6.7.0 | 
 
</details>

<details><summary><strong>Project configuration</strong></summary>

```javascript
// Atviseproject.babel.js

// Insert contents of Atviseproject here
const { Atviseproject, NodeId } = require('atscm');
var IPConfig = require('./IPConfig');

/**
 * atvise-scm configuration of argonics.
 */
class ConfigClass extends Atviseproject {

  /**
   * The atvise-server's host
   * @type {String}
   */
  static get host() {
    return IPConfig.IP;
  }

  /**
   * The atvise-server ports to use.
   * @type {Object}
   * @property {Number} opc The OPC-UA port the atvise-server runs on.
   * @property {Number} http The HTTP port the atvise-server can be reached at.
   */
  static get port() {
    return {
      opc: 4840,
      http: 80,
    };
  }
  
  static get nodes() {
    return([
      new NodeId('Server1'),
      new NodeId('Server2'),
      new NodeId('Server3'),
      new NodeId('Server4'),
      new NodeId('Server5'),
      new NodeId('Server6'),
      new NodeId('SYSTEM')
    ])
  }

}

module.exports = { default: ConfigClass };


</details>

**Comment by LukasHechenberger** [comment]
Supported or not, it should not throw an error. I'll have a look at this one.

Creating a complete *nodes.db* via `atscm push` is about to be supported in version *1.0.0*, currently in beta. You can check out the beta or wait until 1.0.0 is ready.

Create a new project using the current beta by running `atscm init --beta`.

**Comment by Grwmagad** [comment]
Tried with the beta and had no error during the push.

But my servers are missing. Although they are defined at the atviseproject.js and are lying in the src path after the pull.

Everything else seems to be ok.

**Comment by breussm** [comment]
@Grwmagad 
in current version you cannot see the servers?

**Comment by Grwmagad** [comment]
With the current version I get errors everytime the scripts try to create something thats in SYSTEM.LIBRARY....RESSOURCES.
I cannot tell anything about Servers as the script does not get to the point where it creates a server.

**Comment by LukasHechenberger** [comment]
That's right, `atscm push` processes all files inside the project's *src* directory. This is on purpose,  you can instead delete the `./src/SYSTEM` folder before pushing.

**Regarding resource nodes**

I tried to create a resource node via `atscm push` and it worked without any errors. Could you tell us the atvise server version you're using? I checked it out with *atscm v1.0.0-beta.40* and *atserver v3.3.2*...

**Regarding servers**

I was able to reproduce this one, on it.

**Comment by LukasHechenberger** [comment]
Assuming this is fixed in the current release - Feel free to reopen this issue otherwise.
