### ISSUE TITLE
Variables with mirroring to a datasource can´t be pull

### ISSUE THREAD

**Issue by breussm** [atSCM/atscm#3]
![image](https://cloud.githubusercontent.com/assets/11332401/23161157/46d8be9a-f829-11e6-94b1-486e34c11728.png)

**Comment by graphics80** [comment]
Got the same issue, but with the state "BadNodeIdUnknown"
![image](https://cloud.githubusercontent.com/assets/6921785/24091306/a468fbd2-0d47-11e7-8135-0909b6f83249.png)

**Comment by LukasHechenberger** [comment]
@graphics80: Status `BadNodeIdUnknown ` means that the node you're trying to write does not exist. 

Currently, nodes that do not exist on atvise server **are not created** on write. So if the error occurred while trying to write a node that does not yet exist in the atvise server address space, do the following:
 - Create the node using *atvise builder*
 - Pull the newly created node by running `atscm pull`
 - Edit the node's contents on disk
 - Write the changes back by running `atscm push`

Creating nodes while writing is currently a "nice to have", but we are working on it.

**Comment by graphics80** [comment]
Hi @LukasHechenberger the exception `BadNodeIdUnknown` did not happen while `atscm push`, it happen in the initial `atscm pull`.

**Comment by LukasHechenberger** [comment]
I see. What versions of atscm / atscm-cli do you use?

**Comment by breussm** [comment]
![image](https://cloud.githubusercontent.com/assets/11332401/25182295/6f5503c0-2514-11e7-81ad-1309226cbcb6.png)

**Comment by breussm** [comment]
![image](https://cloud.githubusercontent.com/assets/11332401/25182357/a0a04372-2514-11e7-87f6-41b66c2e38fd.png)
