### ISSUE TITLE
Create atvise server nodes on write

### ISSUE THREAD

**Issue by LukasHechenberger** [atSCM/atscm#32]
It would be nice if a node that does not yet exist on atvise server could be created just be creating the corresponding file and running `atscm push`.

Currently new nodes can only be created inside *atvise builder*.

---
*Feature requested in issue #3*

**Comment by LukasHechenberger** [comment]
It turned out, that [node-opcua](https://github.com/node-opcua/node-opcua#supported-features) does not support the OPC-UA *Node Management Service*, so we'll have to implement it ourselves.

**Comment by breussm** [comment]
![image](https://cloud.githubusercontent.com/assets/11332401/25183296/79fcfc80-2517-11e7-9daf-5c4453f0406b.png)

**Comment by breussm** [comment]
![image](https://user-images.githubusercontent.com/11332401/27022887-541419f0-4f50-11e7-9a42-262a931f78a5.png)

If we create nodes we need the information from the properties if they exists. In the current version the properties will not be pulled
