### ISSUE TITLE
atscm watch assertion "expecting existing monitoredItem"

### ISSUE THREAD

**Issue by FKurniawanHuisman** [atSCM/atscm#329]
Hello,

I get the following error when I try to run atscm watch.

> [15:37:28] Using gulpfile D:\DataCompany\HcsStdAtvise\repository\atscm\node_modules\atscm\out\Gulpfile.js
> [15:37:28] Starting 'watch'...
> [15:37:29] Skipped pulling an atvise builder sort order node.
>  Reason: These nodes are not consistent across pulls.
>  You can force pulling them by setting Atviseproject.preserveSortOrderNodes.
> [15:37:30] 'watch' errored after 2.42 s/s)
> [15:37:30] AssertionError [ERR_ASSERTION]: self.monitoredItems[clientHandle], "expecting existing monitoredItem"
>     at new AssertionError (internal/assert.js:269:11)
>     at assert (D:\DataCompany\HcsStdAtvise\repository\atscm\node_modules\better-assert\index.js:32:13)
>     at ClientSubscription._delete_monitored_item (D:\DataCompany\HcsStdAtvise\repository\atscm\node_modules\node-opcua\lib\client\client_subscription.js:599:5)
>     at ClientMonitoredItem.terminate (D:\DataCompany\HcsStdAtvise\repository\atscm\node_modules\node-opcua\lib\client\client_monitored_item.js:88:23)
>     at Timeout.terminate [as _onTimeout] (D:\DataCompany\HcsStdAtvise\repository\atscm\node_modules\atscm\src\lib\server\Watcher.js:102:14)
>     at ontimeout (timers.js:436:11)
>     at tryOnTimeout (timers.js:300:5)
>     at listOnTimeout (timers.js:263:5)
>     at Timer.processTimers (timers.js:223:10)
 
Could you help me?

Thank you.

Kind regards,
Ferry Kurniawan
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            |              Windows 7|
| atscm         |         1.0.0-beta.40 |
| atscm-cli     |                 0.8.2 | 
| atvise server |                 3.3.4 |
| node          |               10.16.3 |
| npm           |                6.11.2 |
 
</details>

<details><summary><strong>Project configuration</strong></summary>

```javascript
// Atviseproject.babel.js

import { Atviseproject, NodeId } from 'atscm';

/**
 * atvise-scm configuration of hcsstdatvise.
 */
export default class Hcsstdatvise extends Atviseproject {

  /**
   * The atvise-server's host
   * @type {String}
   */
  static get host() {
    return 'localhost';
  }

  /**
   * The atvise-server ports to use.
   * @type {Object}
   * @property {Number} opc The OPC-UA port the atvise-server runs on.
   * @property {Number} http The HTTP port the atvise-server can be reached at.
   */
  static get port() {
    return {
      opc: 4840,
      http: 80,
    };
  }

  static get ignoreNodes() {
	return super.ignoreNodes.concat([
		new NodeId('SYSTEM.INFORMATION'),
	]);
  }

}


```

</details>

**Comment by LukasHechenberger** [comment]
I wasn't able to find out what exactly happened, as it seems that the actual error you run into is *hidden* by an error that occurs when terminating pending subscriptions. 

Could you update to *v1.0.0-beta.42* by running `atscm update --beta` and try again? This time you should get a more descriptive error message or even no error at all.

Sorry for the late response.

**Comment by LukasHechenberger** [comment]
Assuming this is fixed in the current release - Feel free to reopen this issue otherwise.
