### ISSUE TITLE
Can´t write from fs to ua node => The node id refers to a node that does not exist in the server address space

### ISSUE THREAD

**Issue by breussm** [atSCM/atscm#33]
![image](https://cloud.githubusercontent.com/assets/11332401/24643546/01cee5f2-190f-11e7-80ac-f412ee373ebc.png)

Tests with atvise 3.1 Release

**Comment by LukasHechenberger** [comment]
Seams to be an encoding issue coming from node-opcua. Workaround on the way...

**Comment by LukasHechenberger** [comment]
@breussm Please review, atscm@0.2.3 should fix this issue

**Comment by breussm** [comment]
[cid:image001.png@01D2AE01.CC291350]

Von: Lukas Hechenberger [mailto:notifications@github.com]
Gesendet: Mittwoch, 05. April 2017 11:09
An: atSCM/atscm <atscm@noreply.github.com>
Cc: BREUSS.Mathias <Mathias.BREUSS@bachmann.info>; Mention <mention@noreply.github.com>
Betreff: Re: [atSCM/atscm] Can´t write from fs to ua node => The node id refers to a node that does not exist in the server address space (#33)


@breussm<https://github.com/breussm> Please review, atscm@0.2.3 should fix this issue

**Comment by LukasHechenberger** [comment]
It turned out, that the tested config was invalid. See https://github.com/atSCM/atscm-cli/issues/9
