### ISSUE TITLE
atscm watch doesn't recognize changes on Global Parameters

### ISSUE THREAD

**Issue by pkoevesdi** [atSCM/atscm#339]
Watch task doesn't react when a global variable is changed in atvise builder.

**Steps to reproduce error**

 - start atscm watch
 - change a node's value under "Global Parameters" in atvise builder -> watch task doesn't react
 - when changing the corresponding .string file, the change gets pushed to the node by the watch task
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | *Windows* |
| atscm         |    1.0.0-beta.43 | 
| atscm-cli     |    0.8.2 | 
| atvise server | 3.3.4 |
| node          |          v12.13.0 | 
| npm           |           6.12.0 | 
 
</details>

<details><summary><strong>Project configuration</strong></summary>

```javascript
import { Atviseproject } from 'atscm';

/**
 * atscm configuration of atscmbeta.
 */
export default class Atscmbeta extends Atviseproject {

  /**
   * The atvise-server's host
   * @type {String}
   */
  static get host() {
    return 'localhost';
  }

  /**
   * The atvise-server ports to use.
   * @type {Object}
   * @property {Number} opc The OPC-UA port the atvise-server runs on.
   * @property {Number} http The HTTP port the atvise-server can be reached at.
   */
  static get port() {
    return {
      opc: 4840,
      http: 80,
    };
  }

} 
```

</details>

**Comment by LukasHechenberger** [comment]
As far as I can tell this is a configuration error - atscm only watches for changes in `AGENT.DISPLAYS` and `SYSTEM.LIBRARY.PROJECT.OBJECTDISPLAYS` by default. 

You can change this by overriding [*Atviseproject.nodesToWatch*](https://atscm.github.io/atscm/class/src/lib/config/Atviseproject.js~Atviseproject.html#static-get-nodesToWatch).

**Example**

```javascript
import { Atviseproject, NodeId } from 'atscm';

/**
 * atscm configuration of atscmbeta.
 */
export default class Atscmbeta extends Atviseproject {

  /**
   * The atvise-server's host
   * @type {String}
   */
  static get host() {
    return 'localhost';
  }

  /**
   * The atvise-server ports to use.
   * @type {Object}
   * @property {Number} opc The OPC-UA port the atvise-server runs on.
   * @property {Number} http The HTTP port the atvise-server can be reached at.
   */
  static get port() {
    return {
      opc: 4840,
      http: 80,
    };
  }

  static get nodesToWatch() {
    return super.nodesToWatch.concat([
      new NodeId('Other.node.you.want.to.watch'),
    ]);
  }

}
```

**Comment by pkoevesdi** [comment]
Ok, I already fiddled around with nodesToWatch(), but wasn't able to find the right syntax.
Now I got it, thank You! 
Is it possible to exclude some of the default nodes that are synced? I'd like to exclude SYSTEM.LIBRARY.ATVISE because of its size. I tried it by using this:

```
static get nodes() {
 return super.nodes.concat([
      new NodeId('AGENT'),
      new NodeId('SYSTEM.DISPLAYS'),
      new NodeId('SYSTEM.GLOBALS'),
      new NodeId('SYSTEM.INFORMATION'),
      new NodeId('SYSTEM.JOURNALS'),
      new NodeId('SYSTEM.LIBRARY.PROJECT'),
      new NodeId('SYSTEM.SECURITY'),
      new NodeId('SYSTEM.TRANSLATIONS'),
      new NodeId('ObjectTypes.PROJECT'),
      new NodeId('VariableTypes.PROJECT')
 ]);
  }
```
which I expect to include the default nodes except SYSTEM.LIBRARY.ATVISE. But SYSTEM.LIBRARY.ATVISE is still pulled. I suppose, the default nodes get added to the ones I define in Atviseproject.babel.js ?
Is there a different way of excluding from the default nodes?

**Comment by pkoevesdi** [comment]
Oh, sorry, the concat is actually the one, that does the adding. I removed it, now it works.

**Comment by pkoevesdi** [comment]
Is there a way to get the same nodes that are synced also to be watched. Just for convinienc to not maintain two times the same list.
Something like:
```
static get nodesToWatch() {
    return nodes();
  }
```

**Comment by LukasHechenberger** [comment]
Yep, you nearly got it right:

- *nodes* and *nodesToWatch* are both getters, so no need for `()`
- They are both static members of your class so, access them via `this`

```javascript
...
  static get nodesToWatch() {
    return this.nodes;
  }
...
```

**Comment by LukasHechenberger** [comment]
BTW This is **by design** not the default. *nodes* contains every node synced, this can easily be a many 100,000 nodes. Watching them all is extremely memory-exhaustive and will most likely kill your node.js VM, as it's limited to 2 GB of memory by default. 

You can try, but I'd recommend you to do everything possible on the local filesystem and just use the builder for the drag-and-drop display-editor.

**Comment by pkoevesdi** [comment]
Ok, thanks You very much for clarification. 
Since I cooked down the synced items to the strictly necessary ~300 nodes (just by taking out the standard library), I dare to watch them all. 
Thank You very much for Your work!

**Comment by pkoevesdi** [comment]
Btw.: when I do `atscm watch`, a browser window opens up unsuccessfully trying to contact `localhost:3000`. Still the watch task works. But it's kind of annoying. Is this worth opening up a new issue?

**Comment by LukasHechenberger** [comment]
Basically, the watch task should open a browser window that reloads itself after every change. Sadly the live-reloading doesn't work everywhere, I'm aware of that and working on a solution.
If *unsuccessfully* means the browser shows a 404 you probably inserted the wrong http port in your config. *ProjectConfig.http* should be set to the port you started your atserver with. 

If the browser shows something different than your atvise app or doesn't appear at all please open a separate issue, with a screenshot of how it looks.
