### ISSUE TITLE
Pull empty atvise project v3.4.0 fails

### ISSUE THREAD

**Issue by FKurniawanHuisman** [atSCM/atscm#355]
1. Create a new atvise project based on template Advanced 1920x1080 (16:9) - Overlay navigation
2. Initialize atscm using `atscm init --beta`
3. Fill all project configuration using default values.
3. Import atscm script using `atscm import`
4. Pull sources using `atscm pull --continue`

> [07:48:32] 'pull' errored after 2.8 s
> [07:48:32] closing tag mismatch
>   63 |          <atv:gridconfig height="20" gridstyle="lines" enabled="false" width="20"/>
>   64 |          <atv:snapconfig height="10" enabled="false" width="10"/>
> > 65 |  </metadata>
>      |  ^ closing tag mismatch
>   66 |  <svg height="580" y="0" width="640" atv:refpy="307.029" atv:refpx="319.992" id="id_1" xlink:href="SYSTEM.LIBRARY.ATVISE.OBJECTDISPLAYS.Advanced.slickgrid.table_panel" transform="matrix(1,0,0,1.0586,0,0)" x="0">
>   67 |          <atv:argument name="tableID" prefix="tableID"/>
>   68 |          <atv:argument name="header_height" prefix="header_height"/>
>  - Node: SYSTEM.LIBRARY.ATVISE.OBJECTDISPLAYS.Advanced.slickgrid.table

![image](https://user-images.githubusercontent.com/54705186/74215898-fc540880-4ca2-11ea-8b7a-5be141b067ad.png)

After checking the SVG, the SVG looks OK. See attachment below.
[SYSTEM.LIBRARY.ATVISE.OBJECTDISPLAYS.Advanced.slickgrid.table.svg.zip](https://github.com/atSCM/atscm/files/4184393/SYSTEM.LIBRARY.ATVISE.OBJECTDISPLAYS.Advanced.slickgrid.table.svg.zip)

---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows |
| atscm         |     1.0.0-beta.46|
| atscm-cli     |     0.9.0 |
| atvise server | 3.4.0|
| node          |          12.14.1 |
| npm           |           6.13.4 |
 
</details>

<details><summary><strong>Project configuration</strong></summary>

```javascript
// Atviseproject.babel.js

import { Atviseproject } from 'atscm';

/**
 * atscm configuration of repository.
 */
export default class Repository extends Atviseproject {

  /**
   * The atvise-server's host
   * @type {String}
   */
  static get host() {
    return 'localhost';
  }

  /**
   * The atvise-server ports to use.
   * @type {Object}
   * @property {Number} opc The OPC-UA port the atvise-server runs on.
   * @property {Number} http The HTTP port the atvise-server can be reached at.
   */
  static get port() {
    return {
      opc: 4840,
      http: 80,
    };
  }

}

```

</details>

**Comment by LukasHechenberger** [comment]
Atvise 3.4 seems to be delivered with standard resources that cause #330. I'll come up with a fix soon but will close this issue as a duplicate. Thanks for reporting, @FKurniawanHuisman!
