### ISSUE TITLE
Using ES2015 not transpile

### ISSUE THREAD

**Issue by breussm** [atSCM/atscm#41]
The transpile process is not working correct.
I took an empty Project, start the watch process copy this code in Main.js

/**
 * Created by breussm on 10.04.2017.
 */
if(true)
{
    let x = 12;
    alert(x); //alert's 12
}

alert(x); //x is undefined here

After saving the watch task write to the node.
The result in the atvise builder is

![image](https://cloud.githubusercontent.com/assets/11332401/24852718/ce33818e-1dd8-11e7-83b3-93d7fabe27ea.png)

**Comment by LukasHechenberger** [comment]
The programming language chosen while running `atscm init` **only applies to the project configuration**. This means that, eventhough you chose *ES2015 JavaScript*, source code inside displays, scripts etc. is written in  regular ES5 JavaScript.

Currently, there is no "official" way to use ES2015 inside source files although you could implement a *custom transformer* that transpiles ES2015 to ES5.
