### ISSUE TITLE
Order from the svg code is not correct

### ISSUE THREAD

**Issue by breussm** [atSCM/atscm#46]
*Insert error description here*
If a specific Display is mirrored to the filesystem and i made changes. The watch task write the node in the wrong order

**Steps to reproduce error**
 - pull the project and start the watch task
 - made change in a js file and save

**Original error message**
- no error message
 
![image](https://cloud.githubusercontent.com/assets/11332401/25735237/27d441ac-316a-11e7-99bf-465fd348b4b9.png)

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows
| atscm         |         0.2.4
| atscm-cli     |         0.2.2 
| atvise server |       3.0.1 
| node          |          6.8.0
| npm           |          3.10.8
 
</details>

<details><summary><strong>Project configuration</strong></summary>

```javascript
// Atviseproject.babel.js

// Insert contents of Atviseproject here
import { Atviseproject, NodeId } from 'atscm';

/**
 * atvise-scm configuration of tessa2015.
 */
export default class Tessa2015 extends Atviseproject {

  /**
   * The atvise-server's host
   * @type {String}
   */
  static get host() {
    return 'localhost';
  }

  /**
   * The atvise-server ports to use.
   * @type {Object}
   * @property {Number} opc The OPC-UA port the atvise-server runs on.
   * @property {Number} http The HTTP port the atvise-server can be reached at.
   */
  static get port() {
    return {
      opc: 4843,
      http: 83,
    };
  }
  
   static get nodes() { 
        return [ 
            new NodeId('AGENT.DISPLAYS'), 
            new NodeId('AGENT.OBJECTS.GlobalServerScripts'), 
            new NodeId('SYSTEM.LIBRARY.PROJECT.MENUSCRIPTS'), 
            new NodeId('SYSTEM.LIBRARY.PROJECT.OBJECTDISPLAYS'),  
            new NodeId('SYSTEM.LIBRARY.PROJECT.QUICKDYNAMICS'), 
            new NodeId('SYSTEM.LIBRARY.PROJECT.RESOURCES'), 
            new NodeId('SYSTEM.LIBRARY.PROJECT.SERVERSCRIPTS'), 
            new NodeId('SYSTEM.LIBRARY.PROJECT.WEBMIMETHODS') 
    ] 
  } 

}


</details>

**Comment by LukasHechenberger** [comment]
Just came across the same error.
[*xml2js* has an issue on that](https://github.com/Leonidas-from-XIV/node-xml2js/issues/31), that is closed, but i didn't take it into account while implementing the display- and script-transformer.
This can be fixed setting the options *explicitChildren*, *preserveChildrenOrder* and *charsAsChildren* options to `true` of the parser, but all child node manipulation has to be done through the `$$` variables. By now child nodes are accessed directly, which means child order cannot be preserved.

**Workaround**

The issue affects only same typed nodes in the same document level, e.g:
```xml
<text></text>
<rect></rect>
<text></text>
```

is build into

```xml
<rect></rect>
<text></text>
<text></text>
```

To prevent this, consider using additional node grouping:

```xml
<text></text>
<g>
  <rect></rect>
  <text></text>
</g>
```

I'll fix that in the next release
