### ISSUE TITLE
push task not working out of the box

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#90]
When setting up atscm project, doing the first pull from server and try to push directly afterward, the push task is not working.

**Steps to reproduce error**

 - atscm init (**Create new Project**)
 - atscm pull
 - atscm push

**Original error message**

![atscm040_pushtest](https://user-images.githubusercontent.com/34569639/34036035-46ed025c-e184-11e7-8e79-208c24ca8009.PNG)
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | *Windows 10* |
| atscm         |         0.4.0 |
| atscm-cli     |     0.3.0 |
| atvise server | 2.5.9 |
| node          |          6.11.4 |
| npm           |           5.6.0 |
 
</details>

<details><summary><strong>Project configuration</strong></summary>

export default class Atscm040Test extends Atviseproject {

    /**
     * The atvise-server's host
     * @type {String}
     */
    static get host(): String {
        return 'localhost';
    }

    /**
     * The atvise-server ports to use.
     * @type {Object}
     * @property {Number} opc The OPC-UA port the atvise-server runs on.
     * @property {Number} http The HTTP port the atvise-server can be reached at.
     */
    static get port(): Object {
        return {
            opc: 4840,
            http: 9000,
        }
    };

    static get ignoreNodes(): String[] {
        return [
            'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberWarnings',
            'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberAlarms',
            'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberInfos',
            'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberInfosDST',
            'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberInfosIST1',
            .....
        ]
    };

}
</details>

**Comment by LukasHechenberger** [comment]
The node `SYSTEM.JOURNALS.ProjectHistory` is ignored by default as it cannot be written by a non-atvise-builder client.
Therefore, when overriding the *ignoreNodes* array in the *Atviseproject* file, this node should be included.

I'd recommend you to extend the default ignored nodes in your config, e.g. by writing

```typescript
// Atviseproject.ts
import { Atviseproject } from 'atscm';

class AtscmIssue90 extends Atviseproject {
  
  ...

  static get ignoreNodes(): String[] {
    return super.ignoreNodes.concat([
      'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberWarnings',
        'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberAlarms',
        'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberInfos',
        'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberInfosDST',
        'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberInfosIST1',
        ...
    ]);
  }

}
```

Please review this solution @IngMichaelMayr and close this issue if extending ignoreNodes solves your problem.

**Comment by IngMichaelMayr** [comment]
Hello,

thanks for the quick response. Unfortunately it didn't change. Same error mesage as bafore

Best regards

**Comment by LukasHechenberger** [comment]
I'm sorry, if you already pulled the project history node you'll have to delete it before pushing to atvise server, e.g. by running:

```bash
rm src/SYSTEM/JOURNALS/ProjectHistory.var.variant.array 
```

**Comment by IngMichaelMayr** [comment]
Thanks this change the behavior. Now it's getting further, but still I'm running into some issue:

![push issue](https://user-images.githubusercontent.com/34569639/34038679-77faf88c-e18d-11e7-8f94-683b24ffee48.PNG)

**Comment by IngMichaelMayr** [comment]
Tried again to pull and push the source with the actual version of atscm.
I'll give you this information is just as debugging help.

**Steps to reproduce error**
* atscm pull
* atscm push

**Original error message**

![atscm-pullpusherror](https://user-images.githubusercontent.com/34569639/35976946-f679e4fa-0ce1-11e8-9371-67b9917586ba.PNG)
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 x 64 |
| atscm         |         v0.7.0-beta.0 |
| atscm-cli     |     v0.3.6 |
| atvise server | v3.2.0 |
| node          |    v9.3.0    |
| npm           |      v5.6.0      |
 
</details>

**Comment by LukasHechenberger** [comment]
As of v0.6.0-beta.11 you can now use the `--continue` flag to make atSCM continue after failure.

This requires atscm-cli v0.5.0 to be installed (e.g. via `npm i -g atscm-cli@beta`).
