### ISSUE TITLE
watch task - ghost changes

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#91]
Sometimes the watch task is pushing some file changes that were not realy made by the user.
The used editor can be excluded as a reason for this problem

**Steps to reproduce error**
Reproduction is currently difficult

 - start atscm watch task
 - change one file
 - check watch task output

**Original error message**

_Information:The file marked with the red arrow have been changed and pushed correctly_

![watch-file-change-issue_1](https://user-images.githubusercontent.com/34569639/34036786-a921de6e-e186-11e7-9940-85001f7cb882.PNG)
![watch-file-change-issue_2](https://user-images.githubusercontent.com/34569639/34036789-aa6273ec-e186-11e7-951b-38200f51c845.PNG)
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | *Windows 10* |
| atscm         |         0.4.0 |
| atscm-cli     |     0.3.0 |
| atvise server | 2.5.9 |
| node          |          6.11.4 |
| npm           |           5.6.0 |
 
</details>

<details><summary><strong>Project configuration</strong></summary>

see other issue created by tis user
</details>

**Comment by LukasHechenberger** [comment]
Could you have a look on this one, @horvathkevin?

**Comment by IngMichaelMayr** [comment]
Hello,

I looked at it but don't see the point. What do you mean?

**Comment by LukasHechenberger** [comment]
Fixed in #169
