### ISSUE TITLE
IgnoredItems - Array

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#92]
When thinking about using a versioning system on the atscm folder structure,
IgnoredItems-Array is realy bad, for the reason that not 100% of the source code will be converted to the file structure and back.

**For example:**

 - Let's say you use git and push your actual code (synced with atscm) to git.
 - After a few weeks you need to do some bugfixes on this pushed source code
 - You take all of it from git and use push on a new NodeOpcUa Server
 - You will not have the 100% Code you had before on this Server

A better approach is appreciated...

**Comment by LukasHechenberger** [comment]
Which nodes are missing when restoring the current git state via `atscm push`?

**Comment by IngMichaelMayr** [comment]
There is no example yet, because i didn't get push task to work for now.
It's more some kind of general thinking...

Wanted to know your opinion on this :-)

**Comment by LukasHechenberger** [comment]
Mainly ignored nodes were introduced for read-only-nodes that exist in every atvise project by default.  In some cases (e.g. when developing a component library) you may also want to just sync parts of a project with atSCM, where ignoredNodes comes in handy as well.
Closing this one, please reopen if you need further information.
