### ISSUE TITLE
Object.entries is not a function when trying to use 0.5.0beta.4

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#94]
When trying to pull with atscm version 0.5.0beta.4 i get this error.

**Steps to reproduce error**

 - Install atscm 0.5.0beta.4
 - init with atscm init
 - run atscm pull

**Original error message**

![atscm050beta4 error pull](https://user-images.githubusercontent.com/34569639/34095253-08fa3baa-e3d1-11e7-8900-d7d9338c7b03.PNG)

 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 |
| atscm         |         0.5.0beta.4 | 
| atscm-cli     |     0.3.0 | 
| atvise server | 2.5.9 |

**Comment by LukasHechenberger** [comment]
Updating nodejs to >= 8 should fix this.

Could you run the failing command with verbose logging (`-LLLL` flag) first so we can find the erroring line of code?

**Comment by IngMichaelMayr** [comment]
Thanks, updating to node version 9.3.0 did the trick.

For sure:
![atscm050-pull-objecterror](https://user-images.githubusercontent.com/34569639/34102362-20e4a936-e3e9-11e7-85db-9f5c592d3815.PNG)

**Comment by LukasHechenberger** [comment]
Thanks!

@horvathkevin: This issue is related to your changes, I’ll assign it to you.

**Comment by LukasHechenberger** [comment]
Closing, as nodejs v8 is required since #125.
