### ISSUE TITLE
Cannot read property 'toString of undefined'

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#96]
When using atscm pull this error occurs.

**Steps to reproduce error**

 - atscm init
 - atscm pull

**Original error message**

![atscm050-pull-tostringerror](https://user-images.githubusercontent.com/34569639/34103174-13673208-e3ec-11e7-8fab-24a04ce62fba.PNG)

 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 |
| atscm         |         0.5.0beta.4 | 
| atscm-cli     |     0.3.0 | 
| atvise server | 3.2.0 |
| node          |          9.3.0 | 
| npm           |           5.6.0 | 
 
</details>

<details><summary><strong>Project configuration</strong></summary>
import { Atviseproject } from 'atscm';

/**
 * atvise-scm configuration of atscm040-test.
 */
export default class Atscm040Test extends Atviseproject {

    /**
     * The atvise-server's host
     * @type {String}
     */
    static get host(): String {
        return 'localhost';
    }

    /**
     * The atvise-server ports to use.
     * @type {Object}
     * @property {Number} opc The OPC-UA port the atvise-server runs on.
     * @property {Number} http The HTTP port the atvise-server can be reached at.
     */
    static get port(): Object {
        return {
            opc: 4840,
            http: 80,
        }
    };

	static get ignoreNodes(): String[] {
        return super.ignoreNodes.concat([
            'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberWarnings',
            'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberAlarms',
            'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberInfos',
            'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberInfosDST',
            'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberInfosIST1',
            'ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberInfosIST2',
            ..........
        ]);
    };
}

</details>

**Comment by horvathkevin** [comment]
Hello Mr.Mayr,

could you attach your nodes.db to this issue?

Best regards,
Kevin Horvath

**Comment by horvathkevin** [comment]
Hello Mr.Mayr,

if you configre the ignored nodes array as follows,
this error should not occur:

static get ignoreNodes(): String[] {
return super.ignoreNodes.concat([
new NodeId('ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberWarnings'),
new NodeId('ns=1;s=AGENT.OBJECTS.LEGACY.Areas.Notification.Visual.Header.numberAlarms'),
.
.
.
.

**Comment by GenMcMayr** [comment]
Ok, thanks. I'll give it try and report back afterwards

**Comment by IngMichaelMayr** [comment]
Okay, thanks. I'll give it a try and report back afterwards

**Comment by IngMichaelMayr** [comment]
I tried your suggested solution, but got the following error:

![atscm pull-issue_atscm050beta4_2](https://user-images.githubusercontent.com/34569639/35516620-7ef15a08-050c-11e8-9955-e9ac18649759.PNG)

So I tried to solve it with the import:
`import { NodeId } from  './node_modules/atscm/src/lib/ua/NodeId';`

that lead to the following message: **Unexpected token import**

Could you please provide more information on how to use NodeId?

Thanks in advance and best regards

**Comment by horvathkevin** [comment]
Hello Mr. Mayr,

you need to change the first line of your configuraion file
as follows:

Import { Atviseproject **, NodeId**} from 'atscm';

Best regards,
Kevin Horvath

**Comment by IngMichaelMayr** [comment]
Good news.
That did the trick. 

Thanks!

Best regards
